name: Docker Hub Deploy

on:
  push:
    branches:
      - 'main'
      - 'master'
    
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: mxpicture
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mxpicture/netbox-device-type-library-import:latest